backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'imagen', widget: 'image' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Category', name: 'category', widget: 'select', options: ["js", "design", "html"] }
      - { label: 'Category222', name: 'category222', widget: 'relation', collection: "categories", valueField: "name", searchFields: ["name"], displayFields: ["name"] }
  - name: 'categories'
    label: 'Categorias'
    format: 'json'
    folder: 'assets/content/categories'
    create: true
    widget: relation
    collection: blog
    searchFields: categories
    valueField: categories
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
